Repository eProsima/Fast-DDS-python, pull requests merged in 2024-07, with the labels that each got.

#151 [21228] Improve CI workflows in 1.2.x, and branching model refactor (backport #149)
  .github/workflows/build_and_test.yml
  .github/workflows/config/build.meta
  .github/workflows/config/ubuntu_test.meta
  .github/workflows/config/windows_test.meta
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/test.meta
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  RELEASE_SUPPORT.md
  fastdds_python.repos
Labels: ci-pending

#153 [21270] Support compilation againt Ubuntu 24.04 swig4.1
  fastdds_python/CMakeLists.txt
  fastdds_python/test/types/CMakeLists.txt
  fastdds_python_examples/HelloWorldExample/CMakeLists.txt
Labels: ready-to-merge

#157 [21137] Account for changes on RTPS writer refactor
  fastdds_python/test/api/test_qos.py
Labels: ready-to-merge

#158 [21329] Update `DataWriter::write` return value as `ReturnCode_t`
  fastdds_python/test/api/test_datareader.py
  fastdds_python/test/api/test_datawriter.py
Labels: ready-to-merge

#149 [21228] Improve CI workflows in main, and branching model refactor
  .github/actions/fetch-fastdds_python-repos/action.yml
  .github/workflows/build_and_test.yml
  .github/workflows/config/build.meta
  .github/workflows/config/ubuntu_test.meta
  .github/workflows/config/windows_test.meta
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/weekly-windows-ci.yml
  .github/workflows/windows-ci.yml
  README.md
  RELEASE_SUPPORT.md
Labels: ready-to-merge

#150 [21228] Improve CI workflows in 1.4.x, and branching model refactor (backport #149)
  .github/actions/fetch-fastdds_python-repos/action.yml
  .github/workflows/build_and_test.yml
  .github/workflows/config/build.meta
  .github/workflows/config/ubuntu_test.meta
  .github/workflows/config/windows_test.meta
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/test.meta
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  README.md
  RELEASE_SUPPORT.md
  fastdds_python.repos
Labels: ci-pending

#152 [21228] Improve CI workflows in 1.0.x, and branching model refactor (backport #149)
  .github/workflows/build_and_test.yml
  .github/workflows/config/build.meta
  .github/workflows/config/ubuntu_test.meta
  .github/workflows/config/windows_test.meta
  .github/workflows/reusable-ubuntu-ci.yml
  .github/workflows/reusable-windows-ci.yml
  .github/workflows/test.meta
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
  README.md
  RELEASE_SUPPORT.md
  fastdds_python.repos
Labels: ci-pending

#161 [21228] Apply missing fixes in CI
  .github/workflows/reusable-ubuntu-ci.yml
  README.md
  RELEASE_SUPPORT.md
Labels: skip-ci

#162 [21310] Set Fast DDS 2.13.x as EOL
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  RELEASE_SUPPORT.md
Labels: skip-ci

#163 [21301] Remove `WriterProxyData` from public APIs
  fastdds_python/src/swig/fastdds.i
  fastdds_python/src/swig/fastdds/dds/builtin/topic/BuiltinTopicKey.i
  fastdds_python/src/swig/fastdds/dds/builtin/topic/PublicationBuiltinTopicData.i
  fastdds_python/src/swig/fastdds/rtps/builtin/data/WriterProxyData.i
  fastdds_python/src/swig/fastdds/rtps/writer/WriterDiscoveryInfo.i
  fastdds_python/test/api/test_datareader.py
Labels: ready-to-merge

#165 [21373] Update to new TopicDataType functions
  fastdds_python/test/types/test_completePubSubTypes.cxx
  fastdds_python/test/types/test_completePubSubTypes.hpp
  fastdds_python/test/types/test_completePubSubTypes.i
  fastdds_python/test/types/test_included_modulesPubSubTypes.cxx
  fastdds_python/test/types/test_included_modulesPubSubTypes.hpp
  fastdds_python/test/types/test_included_modulesPubSubTypes.i
  fastdds_python/test/types/test_modulesPubSubTypes.cxx
  fastdds_python/test/types/test_modulesPubSubTypes.hpp
  fastdds_python/test/types/test_modulesPubSubTypes.i
  fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.cxx
  fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.hpp
  fastdds_python_examples/HelloWorldExample/HelloWorldPubSubTypes.i
Labels: ready-to-merge

#167 [21300] Remove `ReaderProxyData` from public APIs
  fastdds_python/src/swig/fastdds.i
  fastdds_python/src/swig/fastdds/dds/builtin/topic/SubscriptionBuiltinTopicData.i
  fastdds_python/src/swig/fastdds/rtps/builtin/data/ContentFilterProperty.i
  fastdds_python/src/swig/fastdds/rtps/reader/ReaderDiscoveryInfo.i
Labels: ready-to-merge

#168 [21383] Fix tests on Ubuntu 24.04
  fastdds_python/src/swig/fastdds/dds/domain/DomainParticipantFactory.i
  fastdds_python/test/api/test_datareader.py
  fastdds_python/test/api/test_datawriter.py
  fastdds_python/test/api/test_domainparticipant.py
  fastdds_python/test/api/test_domainparticipantfactory.py
  fastdds_python/test/api/test_publisher.py
  fastdds_python/test/api/test_subscriber.py
Labels: ready-to-merge

#170 [21226] Add type support regeneration utility to 1.2.x
  utils/scripts/update_generated_code_from_idl.sh
Labels: skip-ci

#171 [21387] Avoid usage of removed action
  .github/workflows/reusable-windows-ci.yml
Labels: ready-to-merge

#175 [21310] Remove 2.13.x from CI in 1.4.x version
  .github/workflows/ubuntu-ci.yml
  .github/workflows/windows-ci.yml
Labels: ci-pending

#164 [21321] Split `Time_t.i` in `dds::Time_t` and `rtps::Time_t`
  fastdds_python/src/swig/fastdds.i
  fastdds_python/src/swig/fastdds/dds/core/Time_t.i
  fastdds_python/src/swig/fastdds/rtps/common/Time_t.i
Labels: ready-to-merge

#166 [21295] Participant discovery data refactor
  fastdds_python/src/swig/fastdds/rtps/builtin/data/ParticipantProxyData.i
Labels: ci-pending

#169 [21325] Remove all code related to FAST CDR v1
  fastdds_python/src/swig/fastdds.i
  fastdds_python/test/CMakeLists.txt
  fastdds_python/test/api/conftest.py
  fastdds_python/test/api/test_datareader.py
  fastdds_python/test/types/test_complete.i
  fastdds_python/test/types/test_included_modules.i
  fastdds_python/test/types/test_modules.i
  fastdds_python_examples/HelloWorldExample/HelloWorld.i
Labels: ci-pending
