Repository eProsima/Fast-DDS-python, pull requests merged in 2024-10, with the labels that each got.

#190 [21783] Bump version to 2.1.0
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  fastdds_python/CMakeLists.txt
Labels: ci-pending

#191 [21783] Remove unused workflows from 2.0.x & update .repos
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/weekly-windows-ci.yml
  fastdds_python.repos
Labels: skip-ci

#189 [21745] Add tests for new QoS getters from raw XML
  fastdds_python/test/api/DEFAULT_FASTRTPS_PROFILES.xml
  fastdds_python/test/api/test_domainparticipant.py
  fastdds_python/test/api/test_domainparticipantfactory.py
  fastdds_python/test/api/test_publisher.py
  fastdds_python/test/api/test_subscriber.py
  fastdds_python/test/api/test_xml_profile.xml
Labels: ci-pending

#192 [21890] Update commercial support section in project README
  README.md
Labels: skip-ci

#193 [21882] Bump version to 2.2.0
  .github/pull_request_template.md
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  fastdds_python/CMakeLists.txt
Labels: ready-to-merge

#194 [21882] Remove unused workflows from 2.1.x & update .repos
  .github/workflows/mirror.yml
  .github/workflows/nightly-ubuntu-ci.yml
  .github/workflows/nightly-windows-ci.yml
  .github/workflows/ubuntu-ci.yml
  .github/workflows/weekly-ubuntu-ci.yml
  .github/workflows/weekly-windows-ci.yml
  .github/workflows/windows-ci.yml
  fastdds_python.repos
Labels: skip-ci

#188 [21808] Update DataWriter/Reader `get_matched_publication/subscription...()` (2.x) API tests
  fastdds_python/test/api/test_datareader.py
  fastdds_python/test/api/test_datawriter.py
Labels: ci-pending
